SystemOfProductionControl/Models/ActOfSale.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemOfProductionControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActOfSale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActOfSale()
        {
            this.ActOfSaleToProducts = new HashSet<ActOfSaleToProducts>();
        }
    
        public int ID { get; set; }
        public int Company { get; set; }
        public int City { get; set; }
        public string Comment { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual Cities Cities { get; set; }
        public virtual Company Company1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActOfSaleToProducts> ActOfSaleToProducts { get; set; }
    }
}

SystemOfProductionControl/Models/Kit.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemOfProductionControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kit()
        {
            this.KitToProduct = new HashSet<KitToProduct>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KitToProduct> KitToProduct { get; set; }
    }
}

SystemOfProductionControl/Controllers/ActOfSalesController.cs
/*
 *  Не используется на данный момент
 *  ("Продажи"?) используется в _Layout (основное окно)
 */

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using SystemOfProductionControl.Models;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace SystemOfProductionControl.Controllers
{
    public class ActOfSalesController : Controller
    {
        private Entities db = new Entities();

        // GET: ActOfSales
        public ActionResult Index()
        {
            var actOfSale = db.ActOfSale.Include(a => a.Cities).Include(a => a.Company1);
            return View(actOfSale.ToList());
        }

        // GET: ActOfSales/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ActOfSale actOfSale = db.ActOfSale.Find(id);
            if (actOfSale == null)
            {
                return HttpNotFound();
            }
         var products=actOfSale.ActOfSaleToProducts.ToList();
            ViewBag.products = products;
            return View(actOfSale);
        }


        public ActionResult KitTable(int id)
        {
            Kit kit = db.Kit.Find(id);

            var d = PartialView("KitTable", kit);

            return PartialView("KitTable", kit);
            
        }

        // GET: ActOfSales/Create
        public ActionResult Create()
        {
            ViewBag.City = new SelectList(db.Cities, "ID", "Name");
            ViewBag.Company = new SelectList(db.Company, "Id", "Name");
            ViewBag.Kit = new SelectList(db.Kit, "Id", "Name");

            return  View();
        }

        // POST: ActOfSales/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Company,City,Comment,Data")] ActOfSale actOfSale, String[] NameProduct, int?[] Number, int[] CountProduct)
        { 
            if (ModelState.IsValid)
            {
                
                db.ActOfSale.Add(actOfSale);
                db.SaveChanges();


                for (int i = 0; i < NameProduct.Length; i++)
                {

                    String name = NameProduct[i].TrimEnd(' ');
                    Products product = db.Products.FirstOrDefault(t => t.Name == name);
                    if (product != null)
                    {

                        for (int j = 0; j < CountProduct[i]; j++)
                        {  
                        ActOfSaleToProducts ActOfSaleToProducts = new ActOfSaleToProducts();
                        ActOfSaleToProducts.IDAct = actOfSale.ID;
                      
                        ActOfSaleToProducts.IDProduct = product.Id;
                            if (Number[i] != null)
                                ActOfSaleToProducts.Number = Number[i].Value + j;

                            db.ActOfSaleToProducts.Add(ActOfSaleToProducts);
                            db.SaveChanges();
                        }
                     
                    }


                } 
 
              // db.SaveChanges();





                return RedirectToAction("Index");
            }

            ViewBag.City = new SelectList(db.Cities, "ID", "Name");
            ViewBag.Company = new SelectList(db.Company, "Id", "Name");
            ViewBag.Kit = new SelectList(db.Kit, "Id", "Name");


            return View(actOfSale);
        }

        // GET: ActOfSales/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ActOfSale actOfSale = db.ActOfSale.Find(id);
            if (actOfSale == null)
            {
                return HttpNotFound();
            }
            ViewBag.City = new SelectList(db.Cities, "ID", "Name", actOfSale.City);
            ViewBag.Company = new SelectList(db.Company, "Id", "Name", actOfSale.Company);
            List<ActOfSaleToProducts> products = actOfSale.ActOfSaleToProducts.ToList();
            ViewBag.products = products;
            return View(actOfSale);
        }

        // POST: ActOfSales/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Company,City,Comment,Data")] ActOfSale actOfSale)
        {
            if (ModelState.IsValid)
            {
                db.Entry(actOfSale).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.City = new SelectList(db.Cities, "ID", "Name", actOfSale.City);
            ViewBag.Company = new SelectList(db.Company, "Id", "Name", actOfSale.Company);
            return View(actOfSale);
        }

        // GET: ActOfSales/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ActOfSale actOfSale = db.ActOfSale.Find(id);
            if (actOfSale == null)
            {
                return HttpNotFound();
            }
            return View(actOfSale);
        }

        // POST: ActOfSales/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ActOfSale actOfSale = db.ActOfSale.Find(id);
            var product = db.ActOfSaleToProducts.Where(t => t.IDAct == actOfSale.ID);

            db.ActOfSaleToProducts.RemoveRange(product);
            db.SaveChanges();

            db.ActOfSale.Remove(actOfSale);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SystemOfProductionControl/Controllers/KitsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using SystemOfProductionControl.Models;
using System.Web.Mvc;

namespace SystemOfProductionControl.Controllers
{
    public class KitsController : Controller
    {
        private Entities db = new Entities();

        // GET: Kits
        public ActionResult Index()
        {
            return View(db.Kit.ToList());
        }

        // GET: Kits/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kit kit = db.Kit.Find(id);
            if (kit == null)
            {
                return HttpNotFound();
            }
            return View(kit);
        }

        // GET: Kits/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Kits/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name")] Kit kit,String[] NameProduct, int[] CountProduct)
        { 


            if (ModelState.IsValid)
            {
                
                db.Kit.Add(kit);
                db.SaveChanges();

                for (int i = 0; i < NameProduct.Length; i++)
                {
                 
                    String name = NameProduct[i].TrimEnd(' ');
                    Products product = db.Products.Where(t => t.Name==name).FirstOrDefault();
                    if (product != null)
                    {
                        KitToProduct kitToProduct = new KitToProduct();
                        kitToProduct.IDKit = kit.ID;
                        kitToProduct.IDProduct = product.Id;
                        kitToProduct.Default = CountProduct[i];
                        db.KitToProduct.Add(kitToProduct);
                       
                    }
                  

                }

                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(kit);
        }

        // GET: Kits/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kit kit = db.Kit.Find(id);
            if (kit == null)
            {
                return HttpNotFound();
            }
            return View(kit);
        }


        public ActionResult GetProducts()
        {
            var Comp = db.Products.ToList();
            List<string> fd = new List<string>();
            foreach (var item in Comp)
            {
                item.Name = item.Name.TrimEnd(' ');
              
            }



            SelectList d = new SelectList(Comp, "Id", "Name");

            return Json(d, JsonRequestBehavior.AllowGet);
        }

        // POST: Kits/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name")] Kit kit)
        {
            if (ModelState.IsValid)
            {
                db.Entry(kit).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(kit);
        }

        // GET: Kits/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kit kit = db.Kit.Find(id);
            if (kit == null)
            {
                return HttpNotFound();
            }
            return View(kit);
        }

        // POST: Kits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Kit kit = db.Kit.Find(id);
 
        db.KitToProduct.RemoveRange(kit.KitToProduct);
            
                 

            db.Kit.Remove(kit);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SystemOfProductionControl/Views/ActOfSales/Create.cshtml
@model SystemOfProductionControl.Models.ActOfSale
@using SystemOfProductionControl.Models

@{
    ViewBag.Title = "Create";
    SelectList Cities = ViewBag.City;
    SelectList Companies = ViewBag.Company;
    SelectList Kits = ViewBag.Kit;
}

<link rel="stylesheet" href="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.10.3/themes/sunny/jquery-ui.css">


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div>
        <div class="row" style="width: 80vw;margin: auto" ">

            <div class="card" style="width: 80vw;margin: auto">

                <div class="panel panel-default">
                    <br />
                    <div class="card-header">
                        <br />

                        <table cellspacing="5" cellpadding="5" width="100%">
                            <tr>
                                <th style="text-align: center">
                                    Компания
                                </th>
                                <th style="text-align: center">
                                    Город
                                </th>
                                <th style="text-align: center">
                                    Дата
                                </th>
                                <th style="text-align: center">
                                    примечание
                                </th>
                            </tr>


                            <tr style="vertical-align:top">
                                <td>
                                    @Html.DropDownList("Company", Companies, "Нет", htmlAttributes: new { @class = "form-control", @id = "Company", @style = "width: 200px; margin: 10px;" })
                                    @Html.ValidationMessageFor(model => model.Company, "", new { @class = "text-danger" })
                                </td>
                                <td>
                                    @Html.DropDownList("City", Cities, "Нет", htmlAttributes: new { @class = "form-control", @id = "City", @style = "width: 200px; margin: 10px;" })
                                    @Html.ValidationMessageFor(model => model.Company, "", new { @class = "text-danger" })
                                </td>
                                <td>
                                    <input type="date" class="form-control" value="@DateTime.Now.ToString("yyyy-MM-dd")" name="Data" style="margin:10px; width: 200px;">
                                </td>
                                <td>
                                    @Html.TextArea("Comment", "", 4, 50, htmlAttributes: new { @class = "form-control", @id = "CommentText", @style = "margin-left: 20px; margin: 10px;  " });
                                </td>
                            </tr>
                        </table>

                    </div>
                    <div class="card-body" id="Body" style="padding-bottom: 0px;">

                        <h3>Оборудование</h3>
                        <div class="form-group" style="margin-bottom: 0px;">
                            <table>
                                <tr>
                                    <td></td>
                                    <td>
                                        <div class="ui-widget">
                                            <input id="acInput" class="form-control" style="width: 250px;" />
                                        </div>
                                    </td>

                                    <td>
                                        <div style="margin-left: 10px;">  количество: </div>
                                    </td>

                                    <td>

                                        @Html.TextBox("ComponentCount", "0", htmlAttributes: new { @class = "form-control", @style = "width: 100px; margin:10px;" })
                                    </td>

                                    <td>
                                        <button type="button" onclick="AddComponent()" class="btn btn-success btn-sm" style="margin:2px; margin-right:10px;"> <span class="fa fa-plus"></span></button>
                                    </td>
                                    <td width="50px">
                                    </td>
                                    <td>
                                        Комплект:
                                    </td>
                                    <td>
                                        @Html.DropDownList("KitsSelector", Kits, "Нет", htmlAttributes: new { @class = "form-control", @id = "KitsSelector" })
                                    </td>



                                </tr>

                            </table>



                        </div>

                        <div class="form-group" style="margin-bottom: 0px;" id="DataDiv">
                            <table width="100%" class="table" id="TableComponent">
                                <tr>

                                    <th>
                                        Название
                                    </th>
                                    <th>
                                        Количество
                                    </th>

                                    <th>
                                    </th>
                                </tr>

                            </table>



                        </div>


                    </div>


                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary" style="margin-right: 12px">Сохранить</button>
                    </div>

                </div>

            </div>
        </div>
        </div>
    </div>
}
}

@section scripts {

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script>




    function AddComponent() {

       var name = $("#acInput").val();
       var count = $("#ComponentCount").val();
       AddComponentRequest(name, count);
    };



    function RemoveComponent(button) {
        var Components = $(button);

        Components.parent().parent().remove();

    };

    $('#KitsSelector').change(function () {

        var data = { id: $("#KitsSelector").val() };


        $.ajax({
            type: 'get',
            url: '@Url.Action("KitTable", "ActOfSales")',
            data:
                {
                    id: $("#KitsSelector").val()
                },
            success: function ($date2) {
                $('#TableComponent').remove();
                $('#DataDiv').append($date2);

            }
        });

        //$.getJSON("/ActOfSales/KitTable", data, KitRequest);
    });


    function KitRequest(data) {
        $('#TableComponent').remove();
        $('#DataDiv').append(data);

    };


    function AddComponentRequest(name,count) {

        // $("#TableComponent").empty();

        $("#TableComponent").append('<tr> <td>' + name + '<input name="NameProduct" type="hidden" value="' + name + '" /> </td> <td> <input name="Number" type="number" value="" /> </td>  <td> <input name="CountProduct" type="number" value="' + count + '" /> </td> <td>  <button type="button" tabindex="-1" id="CityIdButton" onclick="RemoveComponent(this)" class="btn btn-danger btn-sm" style="margin-left:2px;"> <span class="fa fa-remove"></span></button> </td> </tr>');

    };



    $(function () {

        $.getJSON("/Kits/GetProducts", null, SetAutocomplete);
    });

    function SetAutocomplete(flowers) {

        var mas = Array(flowers.length);

        $.each(flowers, function (i) {
            mas[i] = flowers[i].Text;
        });
        $('#acInput').autocomplete({
            source: mas,
            minLength: 2
        });
    };















    </script>
}

SystemOfProductionControl/Views/ActOfSales/Edit.cshtml
@model SystemOfProductionControl.Models.ActOfSale

@{
    ViewBag.Title = "Create";
    //SelectList Cities = ViewBag.City;
    //SelectList Companies = ViewBag.Company;
    //SelectList Kits = ViewBag.Kit;
}

<link rel="stylesheet" href="http://AJAX.aspnetcdn.com/AJAX/jquery.ui/1.10.3/themes/sunny/jquery-ui.css">


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div>
        <div class="row" style="width: 80vw;margin: auto"">

             <div class="card" style="width: 80vw;margin: auto">

                <div class="panel panel-default">
                    <br />
                    <div class="card-header">
                        <br />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.ID)

                        <table cellspacing="5" cellpadding="5" width="100%">
                            <tr>
                                <th style="text-align: center">
                                    Компания
                                </th>
                                <th style="text-align: center">
                                    Город
                                </th>
                                <th style="text-align: center">
                                    Дата
                                </th>
                                <th style="text-align: center">
                                    примечание
                                </th>
                            </tr>


                            <tr style="vertical-align:top">
                                <td>
                                    @Html.DropDownList("Company", null, "Нет", htmlAttributes: new { @class = "form-control", @id = "Company", @style = "width: 200px; margin: 10px;" })
                                    @Html.ValidationMessageFor(model => model.Company, "", new { @class = "text-danger" })
                                </td>
                                <td>
                                    @Html.DropDownList("City", null, "Нет", htmlAttributes: new { @class = "form-control", @id = "City", @style = "width: 200px; margin: 10px;" })
                                    @Html.ValidationMessageFor(model => model.Company, "", new { @class = "text-danger" })
                                </td>
                                <td>
                                    <input type="date" class="form-control" value="@DateTime.Now.ToString("yyyy-MM-dd")" name="Data" style="margin:10px; width: 200px;">
                                </td>
                                <td>
                                    @Html.TextArea("Comment", @Model.Comment, 4, 50, htmlAttributes: new { @class = "form-control", @id = "CommentText", @style = "margin-left: 20px; margin: 10px;  " });
                                </td>
                            </tr>
                        </table>

                    </div>
                    <div class="card-body" id="Body" style="padding-bottom: 0px;">

                        <h3>Оборудование</h3>
                        <div class="form-group" style="margin-bottom: 0px;">
                            <table>
                                <tr>
                                    <td></td>
                                    <td>
                                        <div class="ui-widget">
                                            <input id="acInput" class="form-control" style="width: 250px;" />
                                        </div>
                                    </td>

                                    <td>
                                        <div style="margin-left: 10px;">  количество: </div>
                                    </td>

                                    <td>

                                        @Html.TextBox("ComponentCount", "0", htmlAttributes: new { @class = "form-control", @style = "width: 100px; margin:10px;" })
                                    </td>

                                    <td>
                                        <button type="button" onclick="AddComponent()" class="btn btn-success btn-sm" style="margin:2px; margin-right:10px;"> <span class="fa fa-plus"></span></button>
                                    </td>
                                    <td width="50px"></td>
 
                                     
                                </tr>

                            </table>



                        </div>

                        <div class="form-group" style="margin-bottom: 0px;" id="DataDiv">
                            <table width="100%" class="table" id="TableComponent">
                                <tr>
                                    <th>
                                    
                                    </th>
                                    <th>
                                        Название
                                    </th>
                                    <th>
                                        Номер
                                    </th>

                                    <th>
                                    </th>
                                </tr>
                                
                              @foreach (var item in @Model.ActOfSaleToProducts)
                              {
                                <tr>
                                    <td>@Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                    @Html.Hidden("ActOfSaleToProductsID", item.ID)</td>
                                    <td>
                                        @item.Products.Name  
                                    </td>
                                    <td>
                                        <input type="text" name="Number" value= @item.Number /> 
                                    </td>

                                    <td>
                                        <button type="button" tabindex="-1" id="CityIdButton" onclick="RemoveComponent(this)" class="btn btn-danger btn-sm" style="margin-left:2px;"> <span class="fa fa-remove"></span></button>

                                    </td>
                                </tr>
                              }

                            </table>



                        </div>


                    </div>


                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary" style="margin-right: 12px">Сохранить</button>
                    </div>

                </div>

            </div>

        </div>
    </div>

}

@section scripts {

       <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    
    <script>




    function AddComponent() {

       var name = $("#acInput").val();
       var count = $("#ComponentCount").val();
       AddComponentRequest(name, count);
    };



    function RemoveComponent(button,ID) {
        var Components = $(button);

        Components.parent().parent().remove();

    };

    $('#KitsSelector').change(function () {

        var data = { id: $("#KitsSelector").val() };


        $.AJAX({
            type: 'get',
            url: '@Url.Action("KitTable", "ActOfSales")',
            data:
                {
                    id: $("#KitsSelector").val()
                },
            success: function ($date2) {
                $('#TableComponent').remove();
                $('#DataDiv').append($date2);

            }
        });

        //$.getJSON("/ActOfSales/KitTable", data, KitRequest);
    });


    function KitRequest(data) {
        $('#TableComponent').remove();
        $('#DataDiv').append(data);

    };


    function AddComponentRequest(name,count) {

        // $("#TableComponent").empty();

        $("#TableComponent").append('<tr> <td>' + name + '<input name="NameProduct" type="hidden" value="' + name + '" /> </td> <td> <input name="Number" type="number" value="" /> </td>  <td> <input name="CountProduct" type="number" value="' + count + '" /> </td> <td>  <button type="button" tabindex="-1" id="CityIdButton" onclick="RemoveComponent(this)" class="btn btn-danger btn-sm" style="margin-left:2px;"> <span class="fa fa-remove"></span></button> </td> </tr>');

    };



    $(function () {

        $.getJSON("/Kits/GetProducts", null, SetAutocomplete);
    });

    function SetAutocomplete(flowers) {

        var mas = Array(flowers.length);

        $.each(flowers, function (i) {
            mas[i] = flowers[i].Text;
        });
        $('#acInput').autocomplete({
            source: mas,
            minLength: 2
        });
    };















    </script>
}

SystemOfProductionControl/Views/ActOfSales/KitTable.cshtml
@model SystemOfProductionControl.Kit


<table width="100%" class="table" id="TableComponent" >

    <tr>

        <th>
            Название
        </th>
        <th>
            Начальный номер
        </th>
        <th>
            Количество
        </th>

        <th>
        </th>
    </tr>

    @foreach (var item in Model.KitToProduct)
    {
        <tr>

            <td>
              @item.Products.Name  <input name="NameProduct" type="hidden" value="@item.Products.Name" />
            </td>
            <td>
                <input name="Number" type="number" value="" />
            </td> 
            <td>
                <input name="CountProduct" type="number" value="@item.Default" /> 
            </td> 
            <td>
                <button type="button" tabindex="-1" id="CityIdButton" onclick="RemoveComponent(this)" class="btn btn-danger btn-sm" style="margin-left:2px;"> <span class="fa fa-remove"></span></button>  
            </td>
         </tr>
    }
</table>

 